In [ ]:
import numpy as np

# Example 1

In [ ]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [ ]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [ ]:
percentage = (A/cal.reshape(1, 4))*100
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Example 2

In [ ]:
B = np.matrix([100, 200, 300, 400])

print(A + B)

[[156.  200.  304.4 468. ]
 [101.2 304.  352.  408. ]
 [101.8 335.  399.  400.9]]


In [ ]:
C = np.matrix([[100],
               [200],
               [300]])

print(A + C)

[[156.  100.  104.4 168. ]
 [201.2 304.  252.  208. ]
 [301.8 435.  399.  300.9]]
