In [ ]:
import numpy as np

# Example 1

In [ ]:
A = np.random.randn(5)

print(A)

[ 0.23895767 -0.22916963  0.23548775  0.29050994  0.94462005]


In [ ]:
print(A.T)

[ 0.23895767 -0.22916963  0.23548775  0.29050994  0.94462005]


In [ ]:
print(np.dot(A, A.T))

1.14177702345543


# Fixed

In [ ]:
A = A.reshape(5, 1)

print(A)

[[ 0.23895767]
 [-0.22916963]
 [ 0.23548775]
 [ 0.29050994]
 [ 0.94462005]]


In [ ]:
print(A.T)

[[ 0.23895767 -0.22916963  0.23548775  0.29050994  0.94462005]]


In [ ]:
print(np.dot(A, A.T))

[[ 0.05710077 -0.05476184  0.0562716   0.06941958  0.22572421]
 [-0.05476184  0.05251872 -0.05396664 -0.06657605 -0.21647822]
 [ 0.0562716  -0.05396664  0.05545448  0.06841153  0.22244645]
 [ 0.06941958 -0.06657605  0.06841153  0.08439602  0.27442151]
 [ 0.22572421 -0.21647822  0.22244645  0.27442151  0.89230703]]
